= Hackathon Quick Start
:toc:
:toc-title: HACKATHON
:toclevels: 3
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[quick-start-intro]]
The {sdk-long-name} provides tools, sample code, and documentation to help you create programs to run on a *locally-deployed* {IC} replica node.

IMPORTANT: Only *macOS* and *Linux* platforms are supported. 

[[before-you-begin]]
== Before you begin

Before you download and install this release of the SDK, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You should have `+node.js+` installed if you want to include the default template files for front-end development in your project.

If you aren't sure how to open a new terminal shall on your local computer or how to install `node.js`, see <<Preliminary steps for newcomers>>.
If you are comfortable meeting the prerequisites without instructions, continue to <<Download and install>>.

[[newcomers]]
== Preliminary steps for newcomers
If this is the first time you are installing developer tools on your computer, you might need to take a few extra steps to prepare your environment.
The instructions here assume that you are using a macOS computer. 

To prepare a development environment on macOS:

. Open a new terminal using the Terminal application. 
+
For example, open Applications, Utilities, then double-click *Terminal* or press Command+spacebar to open Search, then type `terminal`.
+
The terminal is where you are going to execute command-line instructions. 
To execute a command, you type or copy and paste an instruction, then press Enter.
. Check whether you have the Homebrew package manager installed by running the following command:
+
[source,bash]
----
brew --version
----
+
If the command returns version information, continue to the next step.
If Homebrew isn't installed, copy and paste the following command in your terminal:
+
[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
----
. Check whether you have the `node.js` package manager installed by running the following command:
+
[source,bash]
----
node --version
----
+
If the command returns version information, continue to the next step.
If `node.js` isn't installed, copy and paste the following command in your terminal:
+
[source,bash]
----
brew install node
----
. Create a working folder in your home directory.
+
By default, a new terminal shell always opens your home directory with a path like `/Users/<your-user-name>`.
+
You can create a folder called `ic-hackathon` in the directory by running the following command:
+
[source,bash]
----
mkdir ic-hackathon
----
. Change to the new working folder to keep your workspace tidy by running the following command:
+
[source,bash]
----
cd ic-hackathon
----

Now you're ready to install the {sdk-short-name} and get coding!

[[download-and-install]]
== Download and install

If you haven't already done so, the first step is to download the SDK package so that it is available on your local computer.

To download and install:

[arabic]
. Open a terminal shell on your local computer.
+
For example, open Applications, Utilities, then double-click *Terminal* or press Command+spacebar to open Search, then type `terminal`.
. Download and install the SDK package by running the following command:
+
[source,bash]
----
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----
+
This command prompts you to read and accept the license agreement before installing the `+dfx+` command-line interface executable and its dependencies on your local computer.
. Type `+y+` and press Enter to continue with the installation.
+
The command displays information about the components being installed on the local computer.

[[verify-the-sdk-is-ready-to-use]]
== Verify the SDK is ready to use

If the installation script runs without any errors, everything you need to start developing programs that run on the {platform}  will be available on your local computer.

To verify the SDK is ready to use:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Check that you have the SDK developer command-line interface installed and the executable is available in your PATH by running the following command:
+
[source,bash]
----
dfx --version
----
+
The command displays version information for the developer command-line interface similar to the following:
+
[source,bash]
----
dfx 0.5.8
----
. Preview usage information for the other developer command-line interface sub-commands by running the following command:
+
[source,bash]
----
dfx --help
----
+
The command displays usage information for the `+dfx+` parent command and its subcommands.

[[create-a-new-project]]
== Create a new project

You are now ready to create a new project for your first sample application.

To create a new project directory for your first application:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project directory for your first application by running the following commands:
+
[source,bash]
----
dfx new hello
----
+
The `+dfx new hello+` command creates a new `+hello+` project with a default project directory, some template files, and a new Git repository for your project.
. Change to your project directory by running the following command:
+
[source,bash]
----
cd hello
----

[[build-the-project]]
== Build the program

Your new `+hello+` project includes a simple default program in the `+src/hello+` directory that you can compile.

To build the program executable:

. Check that you are still in your project directory by running the following command:
+
[source,bash]
----
pwd
----
+
You should see a path similar to the following:
+
[source,bash]
----
/Users/<your-user-name>/ic-hackathon/hello
----
. View the contents of the source directory for your project directory by running the following command:
+
[source,bash]
----
ls -l src/hello
----
+
Note that the `src/hello` directory includes a default `+main.mo+` program for your project and a `+public+` directory.
For this _Quick start_, you only need to use the `+main.mo+` program.
. Build the executable from the default `+main.mo+` file by running the following command:
+
[source,bash]
----
dfx build
----
You should see output similar to the following:
+
[source,bash]
----
Building canister hello
Building frontend
Bundling frontend assets in the canister
----

[[start-the-local-network-and-deploy]]
== Start the local network and deploy

You now have a program that can be deployed on your local replica network.

[arabic]
. Check that you are still in your project directory by running the following command:
+
[source,bash]
----
pwd
----
+
You should see a path similar to the following:
+
[source,bash]
----
/Users/<your-user-name>/ic-hackathon/hello
----
. Start the {IC} network on your local computer by running the following command:
+
[source,bash]
----
dfx start --background
----
+
Depending on your platform and local security settings, you might see a warning displayed. 
If you are prompted to allow or deny incoming network connections, click *Allow*.
+
The `+--background+` option starts {IC} replica processes then runs them in the background so that you can continue to the next step without opening another terminal shell on your local computer.
. Deploy the default program on the local network by running the following command:
+
[source,bash]
----
dfx canister install hello
----
+
You should see an installation confirmation message for your canister similar to the following:
+
[source,bash]
----
Installing code for canister hello, with canister_id ic:E4DA969A3F8A893397
----
. Call the predefined `+greet+` method in the program by running the following command:
+
[source,bash]
----
dfx canister call hello greet "there" --type string
----
+
This example uses the `+dfx canister call+` command to pass "there" as an argument of type `+string+` to the `+greet+` function.
. Verify the command displays the return value of the `+greet+` function (Hello, there!).
+
For example:
+
[source,bash, subs="quotes"]
----
("Hello, there!")
----

[[modify-the-program]]
== Modify the code and re-deploy

You now have compiled, deployed, and tested your first {proglang} program on your local replica network.
The next step is to try modifying the template code and experimenting on your own.

To modify the template source code:
. Check that you are still in your project directory by running the following command:
+
[source,bash]
----
pwd
----
+
You should see a path similar to the following:
+
[source,bash]
----
/Users/<your-user-name>/ic-hackathon/hello
----
. Change to the source code directory for your project by running the following command:
+
[source,bash]
----
cd src/hello
----
. Open the template `+main.mo+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the `+main.mo+` file:
+
[source,motoko]
----
include::example$actor_hello.mo[]
----
+
This code sample uses the `+public query func+` to define a query method because, in this case, the `+actor_hello+` program doesn't make any changes to the state of the canister or perform any operations that would update the data you are accessing.
+
For more information about using a query call, see link:../introduction-key-concepts{outfilesuffix}#query-calls[query calls] in link:../introduction-key-concepts{outfilesuffix}#canister-state[Canisters include both program and state].
. Build the WebAssembly executable by running the following command:
+
[source,bash]
----
dfx build --skip-frontend
----
. Deploy your updated `+hello+` project on the local network by running the following command:
+
[source,bash]
----
dfx canister install hello
----
. Use `+dfx canister call+` to call the `+myhello+` function by running the following command:
+
[source,bash]
----
dfx canister call hello myhello
----
+
Verify the program displays output similar to the following:
+
[source,bash]
----
debug.print: Hello, World! from DFINITY
----

[[stop-the-local-replica]]
== Stop the local replica

After you finish experimenting with your program, you can stop the local replica process so that it doesn't continue running in the background.

To stop the replica:
. In the terminal, press Control-C to interrupt the local replica process.
. Stop the local replica by running the following command:
+
[source,bash]
----
dfx stop
----

[[next-steps]]
== Next steps

This _Quick start_ touched on only a few key steps to introduce the basic workflow you follow to develop programs of your own.

To explore further, see the tutorials in the link:../developers-guide/tutorials-intro{outfilesuffix}[_SDK Developer Tools_] and examples in the link:../language-guide/motoko{outfilesuffix}[_{proglang} Programming Language Guide_].
